import Head from "next/head";
import { ProductCard } from "@/Components/ProductCard";
import { TrendingIcon } from "@/Components/Icons/TrendingIcon";
import { Color, COLOR_HEX_STRING } from "@/Components/Color";
import { ItemSummary } from "@/types";

export default function Home() {
  const mockData: ItemSummary = {
    itemId: "test",
    itemName: "Test Name",
    itemPrice: 69420,
    itemDescription: "Test Desc",
    itemQuantity: 10,
    itemCategory: "Test Cat",
    hobby: "Test Hob",
    merchantInfo: {
      email: "testEmail@mail.com",
      phoneNumber: "085674566685",
      username: "test",
      role: "MERCHANT",
      profilePicture: undefined,
      gmtCreate: new Date("2023-04-24 12:17:53"),
      gmtModified: new Date("2023-04-24 12:18:00"),
    },
    merchantLevel: "BEGINNER",
    itemImages: [],
    gmtCreate: new Date("2023-04-25 12:17:53"),
    gmtModified: new Date("2023-04-25 12:18:00"),
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="m-0 lg:mx-auto lg:max-w-screen-lg xl:max-w-screen-xl 2xl:max-w-screen-2xl ">
          <div className="flex px-2 pt-3">
            <p className="text-sm font-bold lg:text-lg">
              Section Title, ini yang placeholder (Maybe jadiin component pisah
              nanti)
            </p>
            <TrendingIcon
              htmlColor={COLOR_HEX_STRING[Color.BrightYellow]}
              classNameIcon="h-7 w-7"
            />
          </div>
          <div className="grid grid-cols-2 gap-4  py-2 px-2 lg:grid-cols-5 lg:py-4">
            {Array(13).fill(<ProductCard itemData={mockData} />)}
          </div>
        </div>
      </main>
    </>
  );
}
