import { ItemQuery, urlFirstString } from "@/helper";
import { ItemQueryResult } from "@/types";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function MerchantItem() {
  // Ini spesific 1 item dari sebuah merchang
  // Product Card redirect kesini
  const router = useRouter();

  const { itemId } = router.query;

  //   const pageTitle = `Search ${urlFirstString(q) ?? ""}`;
  const [itemData, setItemData] = useState<ItemQueryResult | undefined>();
  const [pageTitle, setPageTitle] = useState("");
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    const fetchItemData = async () => {
      if (itemId) {
        setIsLoading(true);
        const itemDataFetch = await ItemQuery({
          itemId: urlFirstString(itemId),
        });
        setItemData(itemDataFetch);
        // klo dari itemId harusnya cuman satu, tpi masih array/list karena useCase nya bisa
        // uat search/query yang banyak hasilnya
        setPageTitle(
          itemDataFetch.items[0].itemName +
            "from" +
            itemDataFetch.items[0].merchantInfo.username
        );
        setIsLoading(false);
      }
    };

    fetchItemData();
  }, [itemId]);

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{JSON.stringify(itemData)}</div>
      </main>
    </>
  );
}
