import Head from "next/head";

export default function MerchantItems() {
  // Disini ntar page nge-list items yang lbh detailed
  return (
    <>
      <Head>
        <title>PlaceHolder Merchant items page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Placeholder MerchantPage page</div>
      </main>
    </>
  );
}
