import Head from "next/head";
import { useRouter } from "next/router";

export default function MerchantPage() {
  // Di Page ini ntar show Merchant info dan list2 item mereka (singkat)
  // Ntar ada [merchantName]/item yang lbh detailed

  const router = useRouter();
  const { merchantName } = router.query;

  return (
    <>
      <Head>
        <title>PlaceHolder Merchant Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          Placeholder MerchantPage
          <br />
          MerchantName: {merchantName}
        </div>
      </main>
    </>
  );
}
