import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

//Page yg bwt nampilin list barang2 yg perlu di review & yg sdh di review
export default function Review() {
  return (
    <>
      <Head>
        <title>Review Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto p-4">
          <div className="mx-auto flex min-h-screen min-w-fit max-w-4xl items-center rounded-lg bg-white shadow-[0px_10px_38px_-10px_rgba(22,_23,_24,_0.35),_0px_10px_20px_-15px_rgba(22,_23,_24,_0.2)]"></div>
        </div>
      </main>
    </>
  );
}
